/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health": {
    get: operations["HealthController_health"];
  };
  "/auth/login": {
    post: operations["AuthController_login"];
  };
  "/auth/refresh": {
    post: operations["AuthController_refresh"];
  };
  "/auth/logout": {
    post: operations["AuthController_logout"];
  };
  "/auth/me": {
    get: operations["AuthController_getProfile"];
  };
  "/users/profile": {
    get: operations["UserController_getProfile"];
    put: operations["UserController_updateProfile"];
  };
  "/users/stats": {
    get: operations["UserController_getStats"];
  };
  "/users/addresses": {
    post: operations["UserController_addAddress"];
  };
  "/users/preferences": {
    put: operations["UserController_updatePreferences"];
  };
  "/restaurants/register": {
    post: operations["RestaurantController_publicRegister"];
  };
  "/restaurants": {
    get: operations["RestaurantController_findAll"];
    post: operations["RestaurantController_createRestaurant"];
  };
  "/restaurants/public": {
    get: operations["RestaurantController_findAllPublic"];
  };
  "/restaurants/categories/public": {
    get: operations["RestaurantController_findAllPublicCategories"];
  };
  "/restaurants/public/by-category": {
    get: operations["RestaurantController_findByCategory"];
  };
  "/restaurants/mine": {
    get: operations["RestaurantController_getMine"];
    patch: operations["RestaurantController_updateMine"];
  };
  "/restaurants/mine/stats/dashboard": {
    get: operations["RestaurantController_getDashboardStats"];
  };
  "/restaurants/mine/orders/recent": {
    get: operations["RestaurantController_getRecentOrders"];
  };
  "/restaurants/mine/customers": {
    get: operations["RestaurantController_getCustomers"];
  };
  "/restaurants/{id}": {
    get: operations["RestaurantController_getOne"];
    delete: operations["RestaurantController_remove"];
    patch: operations["RestaurantController_update"];
  };
  "/restaurants/{restaurantId}/categories": {
    get: operations["RestaurantController_listCategories"];
    post: operations["RestaurantController_createCategory"];
  };
  "/restaurants/categories/{id}": {
    delete: operations["RestaurantController_deleteCategory"];
    patch: operations["RestaurantController_updateCategory"];
  };
  "/restaurants/{restaurantId}/items": {
    get: operations["RestaurantController_listItems"];
    post: operations["RestaurantController_createItem"];
  };
  "/restaurants/items/{id}": {
    get: operations["RestaurantController_getItem"];
    delete: operations["RestaurantController_deleteItem"];
    patch: operations["RestaurantController_updateItem"];
  };
  "/restaurants/{id}/approve": {
    patch: operations["RestaurantController_approve"];
  };
  "/restaurants/{id}/suspend": {
    patch: operations["RestaurantController_suspend"];
  };
  "/seed/restaurant-basic": {
    post: operations["SeedController_seedBasic"];
  };
  "/drivers": {
    get: operations["DriverController_findAll"];
  };
  "/drivers/me/location": {
    put: operations["DriverController_updateMyLocation"];
  };
  "/drivers/me/stats": {
    get: operations["DriverController_getMyStats"];
  };
  "/drivers/me/current-orders": {
    get: operations["DriverController_getMyCurrentOrders"];
  };
  "/drivers/me": {
    get: operations["DriverController_getMyProfile"];
    patch: operations["DriverController_updateMyProfile"];
  };
  "/drivers/me/earnings/summary": {
    get: operations["DriverController_getEarningsSummary"];
  };
  "/drivers/me/earnings": {
    get: operations["DriverController_getEarnings"];
  };
  "/drivers/me/history": {
    get: operations["DriverController_getOrderHistory"];
  };
  "/driver/location/update": {
    post: operations["DriverLocationController_updateLocation"];
  };
  "/driver/location/status": {
    post: operations["DriverLocationController_updateStatus"];
  };
  "/driver/orders": {
    get: operations["DriverOrderController_listMyOrders"];
  };
  "/driver/orders/{orderId}": {
    get: operations["DriverOrderController_getOrder"];
  };
  "/driver/orders/{orderId}/accept": {
    post: operations["DriverOrderController_acceptOrder"];
  };
  "/driver/orders/{orderId}/reject": {
    post: operations["DriverOrderController_rejectOrder"];
  };
  "/driver/orders/{orderId}/arrived-restaurant": {
    post: operations["DriverOrderController_arrivedAtRestaurant"];
  };
  "/driver/orders/{orderId}/picked-up": {
    post: operations["DriverOrderController_pickedUpOrder"];
  };
  "/driver/orders/{orderId}/arrived-customer": {
    post: operations["DriverOrderController_arrivedAtCustomer"];
  };
  "/driver/orders/{orderId}/delivered": {
    post: operations["DriverOrderController_deliveredOrder"];
  };
  "/driver/orders/{orderId}/status": {
    post: operations["DriverOrderController_updateOrderStatus"];
  };
  "/notifications": {
    get: operations["NotificationController_getNotifications"];
  };
  "/notifications/unread-count": {
    get: operations["NotificationController_getUnreadCount"];
  };
  "/notifications/stats": {
    get: operations["NotificationController_getStats"];
  };
  "/notifications/{id}/read": {
    put: operations["NotificationController_markAsRead"];
  };
  "/notifications/mark-all-read": {
    post: operations["NotificationController_markAllAsRead"];
  };
  "/notifications/preferences": {
    get: operations["NotificationController_getPreferences"];
    put: operations["NotificationController_updatePreferences"];
  };
  "/notifications/admin/all": {
    get: operations["NotificationController_getAllNotifications"];
  };
  "/notifications/admin/send": {
    post: operations["NotificationController_sendNotification"];
  };
  "/admin/stats": {
    get: operations["AdminController_stats"];
  };
  "/orders": {
    /** Create new order */
    post: operations["OrderController_createOrder"];
  };
  "/orders/customer": {
    /** Get customer orders */
    get: operations["OrderController_getCustomerOrders"];
  };
  "/orders/restaurant": {
    /** Get restaurant orders */
    get: operations["OrderController_getRestaurantOrders"];
  };
  "/orders/{id}": {
    /** Get order by ID */
    get: operations["OrderController_getOrderById"];
  };
  "/orders/{id}/status": {
    /** Update order status */
    put: operations["OrderController_updateOrderStatus"];
  };
  "/orders/stats/restaurant": {
    /** Get restaurant order statistics */
    get: operations["OrderController_getRestaurantStats"];
  };
  "/images/upload": {
    post: operations["ImageController_uploadImage"];
  };
  "/images/{id}": {
    get: operations["ImageController_getImage"];
    delete: operations["ImageController_deleteImage"];
  };
  "/images/{id}/info": {
    get: operations["ImageController_getImageInfo"];
  };
  "/promotions/public": {
    get: operations["PromotionController_findAllPublic"];
  };
  "/global-categories/public": {
    get: operations["GlobalCategoryController_getPublicCategories"];
  };
  "/global-categories/public/popular": {
    get: operations["GlobalCategoryController_getPopularCategories"];
  };
  "/global-categories/public/{slug}": {
    get: operations["GlobalCategoryController_getCategoryBySlug"];
  };
  "/reviews/public": {
    get: operations["ReviewController_findAllPublic"];
  };
  "/reviews/public/stats": {
    get: operations["ReviewController_getStats"];
  };
  "/reviews/my-reviews": {
    get: operations["ReviewController_getMyReviews"];
  };
  "/reviews": {
    post: operations["ReviewController_create"];
  };
  "/reviews/{id}/helpful": {
    put: operations["ReviewController_markHelpful"];
  };
  "/reviews/{id}/unhelpful": {
    put: operations["ReviewController_markUnhelpful"];
  };
  "/reviews/admin": {
    get: operations["ReviewController_findAllForAdmin"];
  };
  "/reviews/admin/{id}/status": {
    put: operations["ReviewController_updateStatus"];
  };
  "/favorites": {
    get: operations["FavoriteController_getMyFavorites"];
    post: operations["FavoriteController_addFavorite"];
    delete: operations["FavoriteController_removeFavoriteByTarget"];
  };
  "/favorites/{id}": {
    delete: operations["FavoriteController_removeFavorite"];
  };
  "/favorites/{id}/view": {
    post: operations["FavoriteController_trackView"];
  };
  "/favorites/stats": {
    get: operations["FavoriteController_getFavoriteStats"];
  };
  "/favorites/recommendations": {
    get: operations["FavoriteController_getRecommendations"];
  };
  "/search/reindex-items": {
    post: operations["SearchController_reindex"];
  };
  "/search/items": {
    get: operations["SearchController_items"];
  };
  "/cart/add": {
    post: operations["CartController_addToCart"];
  };
  "/cart": {
    get: operations["CartController_getCart"];
    delete: operations["CartController_clearCart"];
  };
  "/cart/summary": {
    get: operations["CartController_getCartSummary"];
  };
  "/cart/{id}": {
    put: operations["CartController_updateCartItem"];
    delete: operations["CartController_removeFromCart"];
  };
  "/customer/restaurants": {
    get: operations["CustomerController_getRestaurants"];
  };
  "/demo/seed": {
    post: operations["DemoController_seed"];
  };
  "/demo/restaurants": {
    get: operations["DemoController_restaurants"];
  };
  "/demo/create-driver": {
    post: operations["DemoController_createDemoDriver"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  HealthController_health: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AuthController_login: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_refresh: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_logout: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_getProfile: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  UserController_getProfile: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  UserController_updateProfile: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  UserController_getStats: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  UserController_addAddress: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  UserController_updatePreferences: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  RestaurantController_publicRegister: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  RestaurantController_findAll: {
    parameters: {
      query?: {
        ownerUserId?: string;
        status?: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  RestaurantController_createRestaurant: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  RestaurantController_findAllPublic: {
    parameters: {
      query: {
        limit: number;
        skip: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  RestaurantController_findAllPublicCategories: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  RestaurantController_findByCategory: {
    parameters: {
      query?: {
        category?: string;
        limit?: number;
        skip?: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  RestaurantController_getMine: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  RestaurantController_updateMine: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  RestaurantController_getDashboardStats: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  RestaurantController_getRecentOrders: {
    parameters: {
      query: {
        limit: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  RestaurantController_getCustomers: {
    parameters: {
      query: {
        page: number;
        limit: number;
        sortBy: string;
        sortOrder: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  RestaurantController_getOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  RestaurantController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  RestaurantController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  RestaurantController_listCategories: {
    parameters: {
      path: {
        restaurantId: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  RestaurantController_createCategory: {
    parameters: {
      path: {
        restaurantId: string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  RestaurantController_deleteCategory: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  RestaurantController_updateCategory: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  RestaurantController_listItems: {
    parameters: {
      query?: {
        type?: string;
        categoryId?: string;
        isActive?: string;
        sortBy?: "position" | "createdAt" | "price";
        order?: "asc" | "desc";
      };
      path: {
        restaurantId: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  RestaurantController_createItem: {
    parameters: {
      path: {
        restaurantId: string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  RestaurantController_getItem: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  RestaurantController_deleteItem: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  RestaurantController_updateItem: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  RestaurantController_approve: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  RestaurantController_suspend: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  SeedController_seedBasic: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  DriverController_findAll: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  DriverController_updateMyLocation: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  DriverController_getMyStats: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  DriverController_getMyCurrentOrders: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  DriverController_getMyProfile: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  DriverController_updateMyProfile: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  DriverController_getEarningsSummary: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  DriverController_getEarnings: {
    parameters: {
      query: {
        fromDate: string;
        toDate: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  DriverController_getOrderHistory: {
    parameters: {
      query: {
        status: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  DriverLocationController_updateLocation: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  DriverLocationController_updateStatus: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  DriverOrderController_listMyOrders: {
    parameters: {
      query: {
        status: string;
        page: string;
        limit: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  DriverOrderController_getOrder: {
    parameters: {
      path: {
        orderId: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  DriverOrderController_acceptOrder: {
    parameters: {
      path: {
        orderId: string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  DriverOrderController_rejectOrder: {
    parameters: {
      path: {
        orderId: string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  DriverOrderController_arrivedAtRestaurant: {
    parameters: {
      path: {
        orderId: string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  DriverOrderController_pickedUpOrder: {
    parameters: {
      path: {
        orderId: string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  DriverOrderController_arrivedAtCustomer: {
    parameters: {
      path: {
        orderId: string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  DriverOrderController_deliveredOrder: {
    parameters: {
      path: {
        orderId: string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  DriverOrderController_updateOrderStatus: {
    parameters: {
      path: {
        orderId: string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  NotificationController_getNotifications: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
        type?: string;
        status?: string;
        unreadOnly?: boolean;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  NotificationController_getUnreadCount: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  NotificationController_getStats: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  NotificationController_markAsRead: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  NotificationController_markAllAsRead: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  NotificationController_getPreferences: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  NotificationController_updatePreferences: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  NotificationController_getAllNotifications: {
    parameters: {
      query: {
        page: number;
        limit: number;
        userId: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  NotificationController_sendNotification: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  AdminController_stats: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  /** Create new order */
  OrderController_createOrder: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  /** Get customer orders */
  OrderController_getCustomerOrders: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  /** Get restaurant orders */
  OrderController_getRestaurantOrders: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  /** Get order by ID */
  OrderController_getOrderById: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  /** Update order status */
  OrderController_updateOrderStatus: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  /** Get restaurant order statistics */
  OrderController_getRestaurantStats: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  ImageController_uploadImage: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  ImageController_getImage: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ImageController_deleteImage: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ImageController_getImageInfo: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  PromotionController_findAllPublic: {
    parameters: {
      query: {
        limit: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  GlobalCategoryController_getPublicCategories: {
    parameters: {
      query?: {
        featured?: boolean;
        limit?: number;
        skip?: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  GlobalCategoryController_getPopularCategories: {
    parameters: {
      query?: {
        limit?: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  GlobalCategoryController_getCategoryBySlug: {
    parameters: {
      path: {
        slug: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ReviewController_findAllPublic: {
    parameters: {
      query?: {
        type?: "restaurant" | "item" | "driver" | "order";
        restaurantId?: string;
        itemId?: string;
        driverId?: string;
        limit?: number;
        skip?: number;
        rating?: number;
        featured?: boolean;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ReviewController_getStats: {
    parameters: {
      query?: {
        type?: "restaurant" | "item" | "driver" | "order";
        restaurantId?: string;
        itemId?: string;
        driverId?: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ReviewController_getMyReviews: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  ReviewController_create: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  ReviewController_markHelpful: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ReviewController_markUnhelpful: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ReviewController_findAllForAdmin: {
    parameters: {
      query: {
        status: string;
        type: string;
        page: number;
        limit: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ReviewController_updateStatus: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  FavoriteController_getMyFavorites: {
    parameters: {
      query?: {
        type?: "restaurant" | "item" | "category";
        limit?: number;
        skip?: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  FavoriteController_addFavorite: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  FavoriteController_removeFavoriteByTarget: {
    parameters: {
      query?: {
        type?: "restaurant" | "item" | "category";
        restaurantId?: string;
        itemId?: string;
        categoryId?: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  FavoriteController_removeFavorite: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  FavoriteController_trackView: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  FavoriteController_getFavoriteStats: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  FavoriteController_getRecommendations: {
    parameters: {
      query?: {
        limit?: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  SearchController_reindex: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  SearchController_items: {
    parameters: {
      query?: {
        restaurantId?: string;
        size?: number;
        q?: unknown;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  CartController_addToCart: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  CartController_getCart: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  CartController_clearCart: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  CartController_getCartSummary: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  CartController_updateCartItem: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  CartController_removeFromCart: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  CustomerController_getRestaurants: {
    parameters: {
      query?: {
        category?: string;
        limit?: number;
        skip?: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  DemoController_seed: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  DemoController_restaurants: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  DemoController_createDemoDriver: {
    responses: {
      201: {
        content: never;
      };
    };
  };
}
